-- =============================================================================
-- CITU-Bandwidth Monitoring System (WildConnect)
-- Database Schema for MySQL
-- 
-- Usage:
--   1. Open MySQL Workbench, connect as root (password: csit*321)
--   2. File > Open SQL Script > select this file
--   3. Execute (Ctrl+Shift+Enter)
--   4. Then start the Spring Boot backend — it will sync any remaining columns
--      via `spring.jpa.hibernate.ddl-auto=update`
-- =============================================================================

CREATE DATABASE IF NOT EXISTS citu_bandwisth
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE citu_bandwisth;

-- -------------------------------------------------------------------------
-- 1. users
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id           BIGINT          NOT NULL AUTO_INCREMENT,
    school_id    VARCHAR(20)     NOT NULL,
    password     VARCHAR(255)    NOT NULL,
    email        VARCHAR(100)    NOT NULL,
    role         VARCHAR(255)    NOT NULL DEFAULT 'USER',
    status       VARCHAR(255)    NOT NULL DEFAULT 'ACTIVE',
    device_brand VARCHAR(50)     DEFAULT NULL,
    device_model VARCHAR(50)     DEFAULT NULL,
    created_at   DATETIME        DEFAULT CURRENT_TIMESTAMP,
    updated_at   DATETIME        DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    UNIQUE KEY uk_users_school_id (school_id),
    UNIQUE KEY uk_users_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -------------------------------------------------------------------------
-- 2. devices
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS devices (
    id           BIGINT          NOT NULL AUTO_INCREMENT,
    user_id      BIGINT          NOT NULL,
    brand        VARCHAR(50)     NOT NULL,
    model        VARCHAR(50)     NOT NULL,
    mac_address      VARCHAR(17)     DEFAULT NULL,
    ip_address       VARCHAR(45)     DEFAULT NULL,
    approval_status  VARCHAR(255)    NOT NULL DEFAULT 'APPROVED',
    is_active        TINYINT(1)      DEFAULT 1,
    created_at   DATETIME        DEFAULT CURRENT_TIMESTAMP,
    updated_at   DATETIME        DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    KEY idx_devices_user_id (user_id),
    CONSTRAINT fk_devices_user FOREIGN KEY (user_id) REFERENCES users(id)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -------------------------------------------------------------------------
-- 3. bandwidth_usage
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS bandwidth_usage (
    id                 BIGINT       NOT NULL AUTO_INCREMENT,
    user_id            BIGINT       NOT NULL,
    device_id          BIGINT       NOT NULL,
    usage_amount       DOUBLE       NOT NULL,
    unit               VARCHAR(255) NOT NULL DEFAULT 'MB',
    timestamp          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    connection_status  VARCHAR(255) DEFAULT 'CONNECTED',

    PRIMARY KEY (id),
    KEY idx_bandwidth_user_id (user_id),
    KEY idx_bandwidth_device_id (device_id),
    CONSTRAINT fk_bandwidth_user FOREIGN KEY (user_id) REFERENCES users(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_bandwidth_device FOREIGN KEY (device_id) REFERENCES devices(id)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =============================================================================
-- Seed data  (optional — uncomment after backend has hashed the password)
-- =============================================================================
-- After starting the backend once, register an admin via POST /api/auth/register
-- with body: { "schoolId":"admin","password":"admin123","email":"admin@citu.edu.ph" }
-- Then manually promote the role:
--   UPDATE users SET role = 'ADMIN' WHERE school_id = 'admin';
--
-- Or use the INSERT below with a BCrypt hash generated by the backend.
-- Generate one by registering temporarily, copy the hash, then use it here:
--
-- INSERT INTO users (school_id, password, email, role, status)
-- VALUES ('admin', '<bcrypt-hash-from-backend>', 'admin@citu.edu.ph', 'ADMIN', 'ACTIVE');
